name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Source Code (Retrieve Repository)
        uses: actions/checkout@master

      - name: 💎 Setup Ruby & Install Dependencies (Prepare Ruby Environment)
        uses: ruby/setup-ruby@master
        with:
          bundler-cache: true

      - name: Precompile Assets
        run: RAILS_ENV=production bundle exec rails assets:precompile

      - name: Generate Self-Signed Certificates
        run: |
          openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost" -keyout localhost.key -out localhost.crt
          mkdir -p config/credentials
          mv zero.key config/credentials/zero.key
          mv zero.crt config/credentials/zero.crt

      - name: Start Rails Server
        run: |
          bundle exec rails s -b 'ssl://0.0.0.0:3000?key=config/credentials/zero.key&cert=config/credentials/zero.crt' -e production &
          sleep 5

      - name: Generate Static HTML from Rails App
        run: wget --https-only --secure-protocol=auto --no-check-certificate --cut-dirs=1 -nH -P ./static-website -mkEpnp https://0.0.0.0:3000

      - name: Upload artifact
        uses: actions/upload-pages-artifact@master
        with:
          path: './static-website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: './static-website'